# Generated by Django 3.0.4 on 2020-03-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': 'supplies'},
        ),
    ]
