# Generated by Django 3.0.4 on 2020-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_auto_20200401_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(default='LastName', max_length=128),
            preserve_default=False,
        ),
    ]
