# Generated by Django 3.0.4 on 2020-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20200404_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
