# Generated by Django 3.0.4 on 2020-04-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_supplier_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='is_validated',
        ),
    ]
