# Generated by Django 3.0.4 on 2020-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_remove_supply_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(default='pbkdf2_sha256$180000$tZiRRKAXPMNy$ptZR5hYoDvG99RHG2qnPFWwzcYPRmaP12IwTW04ucVo=', max_length=20),
        ),
    ]
