# Generated by Django 3.0.4 on 2020-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20200404_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Department of Argriculture', max_length=128),
            preserve_default=False,
        ),
    ]
